<header style="display: flex; height: 120px; background-color: #04254b; justify-content: space-between; align-items: center; padding: 20px">
    <div style="display: flex; align-items: center;">
        <img style="height: 170px; width: 160px; margin-right: 10px" src="IMG/logotipo.png">
        <h1 style="font-size: 50px; margin: 0; font-family: inherit; color: #b6c0c1">Giga Shop</h1>
    </div>
</header>
